### ISSUE TITLE
Hello, author, I have some code problems to ask you

### ISSUE THREAD

**Issue by Anxiaoou** [mindflow-institue/DAEFormer#11]
Hello, author. First of all, thank you very much for your selfless provision of the code. I have some small questions to ask you, why did I modify the dataset into my own dataset and perform binary segmentation, dice and HD are all 0 in the test

**Comment by rezazad68** [comment]
Hi thanks for your interest. If you get a zero dice score it means that there is an issue with your dataset preparation. If you are using a public dataset, please check a public repository to see how they set the learning rate, data preparation and etc to make sure you can adapt it for our code.
