### ISSUE TITLE
how train the skin disease dataset？

### ISSUE THREAD

**Issue by TWENTY-FOU** [mindflow-institue/DAEFormer#12]
Hello dear author, how does your model train the skin disease dataset?I cannot achieve training ISIC datasets！ Can you show me the code you used to train the skin disease dataset? I am a student from Yunnan University, and your code is only for learning! Thank you very much。

**Comment by amirhossein-kz** [comment]
Hi @TWENTY-FOU,

Thanks for your interest. Please check out [DeformableLKA](https://github.com/mindflow-institue/deformableLKA/tree/main/2D) and [TransNorm](https://github.com/rezazad68/transnorm).
