### ISSUE TITLE
using X2 as an input for the key?

### ISSUE THREAD

**Issue by Angelinayanga** [mindflow-institue/DAEFormer#13]
keys = x2.transpose(1, 2)
queries = **x2**.transpose(1, 2)
values = x1.transpose(1, 2)
 
As shown in bold font above，I cannot understand the reason that using X2 as an input for the key.The figure of SCCA in this paper shows that the key from X1.

**Comment by amirhossein-kz** [comment]
Hi @Angelinayanga,
Thank you very much for your interest in our repo. You are right. 
The code is correct and will update the figure in the paper soon. Thanks!
