### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by Ehteshamciitwah** [mindflow-institue/DAEFormer#5]
Hello, Thank you for sharing your work. I would like to train my custom dataset which is 3-channel real RGB images. But during training am facing a problem in inference beacuse of the image channel. what kind of changing I need to do in your code for the custom dataset? The training part is right but shows an error in inference. What kind of changing I need to do in the inference part to find metrics for evaluation? Thank you

**Comment by amirhossein-kz** [comment]
Hi, thank you very much for your interest in our repo. 

The inference is designed for the Synapse dataset, and you need to make some changes in the ```test_single_volume``` function located in ```utils.py```  and ```inference```. Check out the sample code below.

```python
def test_single_volume(image, label, net, classes):

    x_transforms = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.5], [0.5])
    ])
    input = x_transforms(image).float().cuda()[None, ...]

    net.eval()
    with torch.no_grad():
        outputs = net(input)
        out = torch.argmax(torch.softmax(outputs, dim=1), dim=1).squeeze(0)
        prediction = out.cpu().detach().numpy()

    metric_list = []
    for i in range(1, classes):
        metric_list.append(calculate_metric_percase(prediction == i, label == i))

    return metric_list

image = np.random.rand(224, 224, 3)
label = np.random.rand(224, 224)
net = DAEFormer()
metric = test_single_volume(image, label, net, classes=9)
```
